
import { GoogleGenAI, GenerateContentResponse } from "@google/genai";
import { EditRequest } from "../types";

export const editImage = async (request: EditRequest): Promise<string> => {
  // Fix: Initializing GoogleGenAI with named parameter apiKey from process.env.API_KEY directly
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  const imagePart = {
    inlineData: {
      mimeType: request.mimeType,
      data: request.image.split(',')[1], // Remove metadata prefix
    },
  };

  const textPart = {
    text: request.prompt,
  };

  try {
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: { parts: [imagePart, textPart] },
    });

    if (!response.candidates?.[0]?.content?.parts) {
      throw new Error("No image generated by the model.");
    }

    // Iterate through parts to find the image
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }

    throw new Error("The model did not return an edited image part.");
  } catch (error: any) {
    console.error("Gemini Edit Error:", error);
    throw new Error(error.message || "Failed to process image editing.");
  }
};
